//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMXFromDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Product1 = new HashSet<Product>();
            this.Product11 = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string PriceTicker { get; set; }
        public int ProductGroupId { get; set; }
        public decimal LotSize { get; set; }
        public int PeriodResolution { get; set; }
        public int ProductDefinitionId { get; set; }
        public int ProductTypeId { get; set; }
        public bool IsBalance { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public System.DateTime DeliveryFromDate { get; set; }
        public System.DateTime DeliveryToDate { get; set; }
        public int Year { get; set; }
        public Nullable<int> WeeklyPatternId { get; set; }
        public int ProductNumber { get; set; }
        public Nullable<int> ProductParentId { get; set; }
        public Nullable<int> SecondProductParentId { get; set; }
        public int NumberOfChildProducts { get; set; }
        public int NumberOfGrandChildProducts { get; set; }
        public int ToLocationId { get; set; }
        public Nullable<int> FromLocationId { get; set; }
        public System.DateTime CeaseDate { get; set; }
        public System.DateTime TradingFromDate { get; set; }
        public System.DateTime TradingToDate { get; set; }
        public Nullable<System.DateTime> OptionCeaseDate { get; set; }
        public Nullable<System.DateTime> OptionTradingFrom { get; set; }
        public Nullable<System.DateTime> OptionTradingTo { get; set; }
        public string OptionPriceTicker { get; set; }
        public string OptionNameFormat { get; set; }
        public string OptionCallName { get; set; }
        public string OptionPutName { get; set; }
        public string ProductTypeCode { get; set; }
        public string IsinCode { get; set; }
        public string AiiCode { get; set; }
        public int CascadingLevel { get; set; }
        public Nullable<long> TreeId { get; set; }
        public int ProductCategory { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<int> ExternalId { get; set; }
        public int EntityStatus { get; set; }
        public int ExchangeId { get; set; }
        public string TimeZoneId { get; set; }
        public Nullable<int> NumberOfStrikeDecimals { get; set; }
        public string DeliveryCode { get; set; }
        public bool IgnoreDst { get; set; }
        public string FriendlyName { get; set; }
        public string ExternalName { get; set; }
        public string OptionFriendlyName { get; set; }
        public string OptionExternalName { get; set; }
        public string FamiliyName { get; set; }
        public string OptionLogicalCode { get; set; }
        public string LogicalCode { get; set; }
        public string ClearerCode { get; set; }
        public string InternalName { get; set; }
        public int CommodityId { get; set; }
        public Nullable<int> SpreadCommodityId { get; set; }
        public Nullable<bool> SoftNumStrikeDecRule { get; set; }
        public string Description { get; set; }
        public string OptionClearerCode { get; set; }
        public string OptionIsinCode { get; set; }
    
        public virtual ProductGroup ProductGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product1 { get; set; }
        public virtual Product Product2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product11 { get; set; }
        public virtual Product Product3 { get; set; }
        public virtual ProductDefinition ProductDefinition { get; set; }
    }
}
