//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMXFromDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDefinition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductDefinition()
        {
            this.Products = new HashSet<Product>();
            this.ProductDefinitionTrees = new HashSet<ProductDefinitionTree>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ProductGroupId { get; set; }
        public int ToLocationId { get; set; }
        public Nullable<int> FromLocationId { get; set; }
        public Nullable<int> WeeklyPatternId { get; set; }
        public int PeriodResolution { get; set; }
        public int LotUnitId { get; set; }
        public int MarketSettlementType { get; set; }
        public int DeliveryType { get; set; }
        public int CloseOutType { get; set; }
        public int CascadingType { get; set; }
        public int TradeOrderType { get; set; }
        public bool AutoExerciseOption { get; set; }
        public bool AlwaysAllowCascadingUpdate { get; set; }
        public short NumberOfPriceDecimals { get; set; }
        public short NumberOfLotDecimals { get; set; }
        public string Region { get; set; }
        public string Sector { get; set; }
        public string TimeZoneId { get; set; }
        public string DefinitionTypeCode { get; set; }
        public int DefaultPriceUnitId { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<int> ExternalId { get; set; }
        public int EntityStatus { get; set; }
        public Nullable<int> IndeliveryPriceModelId { get; set; }
        public decimal LotSize { get; set; }
        public int ExchangeId { get; set; }
        public int MarketSettlementOptionType { get; set; }
        public bool NoUnrealisedInDelivery { get; set; }
        public int ProductCategory { get; set; }
        public int OptionExerciseType { get; set; }
        public bool SupportOption { get; set; }
        public bool IgnoreDst { get; set; }
        public int InstrumentType { get; set; }
        public int CommodityId { get; set; }
        public Nullable<int> SpreadCommodityId { get; set; }
        public Nullable<int> SplittingResolution { get; set; }
        public Nullable<int> PositionTypeId { get; set; }
        public int OptionPremiumType { get; set; }
        public Nullable<int> ClearingGroupId { get; set; }
        public string InternalName { get; set; }
        public string LoadType { get; set; }
        public string SpecificationUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        public virtual ProductGroup ProductGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDefinitionTree> ProductDefinitionTrees { get; set; }
    }
}
