//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMXFromDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDefinitionTree
    {
        public int ProductTypeId { get; set; }
        public int ProductCascadingLevel { get; set; }
        public int ProductDefinitionId { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
    
        public virtual ProductDefinition ProductDefinition { get; set; }
    }
}
